wrist_camera_node:
  ros__parameters:
    serial: "260322273823"
    width: 848
    height: 480
    fps: 30
    frame_id: "camera_color_optical_frame"
    topic: "realsense/frame"


yolo_detector_node:
  ros__parameters:
    yolo_model_path: "/ros2_ws/src/port_pose_estimator/models/0719_yolo.pt"
    confidence_threshold: 0.5

